const express=require('express')
const app=express()
const port=8000
app.use(express.json())
let cars=[
    {
        id:1,
        name:"alto",
        prices:100
    },
    {
        id:2,
        name:"alto",
        prices:100
    },
    {
        id:3,
        name:"alto",
        prices:100
    },
    {
        id:4,
        name:"alto",
        prices:100
    },
    {
        id:5,
        name:"alto",
        prices:100
    },
    {
        id:6,
        name:"alto",
        prices:100
    },
    {
        id:7,
        name:"maruti",
        prices:100
    },
    {
        id:8,
        name:"maruti",
        prices:100
    },
    {
        id:9,
        name:"maruti",
        prices:100
    },
    {
        id:10,
        name:"maruti",
        prices:100
    },
    {
        id:11,
        name:"maruti",
        prices:100
    },
    {
        id:12,
        name:"maruti",
        prices:100
    },
    {
        id:13,
        name:"bmw",
        prices:100
    },
    {
        id:14,
        name:"bmw",
        prices:100
    },
    {
        id:15,
        name:"bmw",
        prices:100
    }
]
app.listen(port,()=>{
    console.log(`server is running on http://localhost:${port}`)
})